# Docker compose file for running (and scaling) a set of OODT services on a single Docker host
# Example usage:
# docker-compose up -d
# docker-compose scale oodt_wmgr=4
# 
# NOTE: this compose file is NOT suitable for running multiple OODT containers on a Docker swarm

version: '2'

services:

  oodt-filemgr:
    image: oodthub/oodt-filemgr:0.3
    expose:
      - "9000"
    ports:
      - "9000:9000"
    volumes:
      - ./workflows/test-workflow/policy:/usr/local/oodt/workflows/policy
    volumes_from:
      - oodt-resmgr

  oodt-wmgr:
    image: oodthub/oodt-wmgr:0.3
    expose:
      - "9001"
    ports:
      - "9001:9001"
    volumes:
      - ./workflows/test-workflow/policy:/usr/local/oodt/workflows/policy
      - ./workflows/test-workflow/pge-configs:/usr/local/oodt/workflows/test-workflow/pge-configs
      - ./pges/test-workflow:/usr/local/oodt/pges/test-workflow
      - ./conf/workflow.properties:/usr/local/oodt/cas-workflow/etc/workflow.properties
    environment:
      - FILEMGR_URL=http://oodt-filemgr:9000
      - RESMGR_URL=http://oodt-resmgr:9002

  oodt-fmprod:
    image: oodthub/oodt-fmprod:0.3
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes_from:
      - oodt-resmgr
    environment:
      - FILEMGR_URL=http://oodt-filemgr:9000

  oodt-resmgr:
    image: oodthub/oodt-resmgr:0.3
    expose:
      - "9002"
      - "2001"
    ports:
      - "9002:9002"
      - "2001:2001"
    volumes:
      - ./workflows/test-workflow/policy:/usr/local/oodt/workflows/policy
      - ./workflows/test-workflow/pge-configs:/usr/local/oodt/workflows/test-workflow/pge-configs
      - ./pges/test-workflow:/usr/local/oodt/pges/test-workflow
    environment:
      - WORKFLOW_URL=http://oodt-wmgr:9001
      - RESMGR_HOME=/usr/local/oodt/cas-resource
