# docker-compose configuration for running the labcas-test workflow

version: '2'

services:

  # OODT File Manager + LabCAS configuration
  oodt_filemgr_app:
    env_file: labcas.env
    image: oodthub/oodt-filemgr
    container_name: oodt_filemgr
    expose:
      - "9000"
      - "8983"
    ports:
      - "8983:8983"
      - "9000:9000"
    volumes:
      - $PWD/filemgr/etc/filemgr.properties:/usr/local/oodt/cas-filemgr/etc/filemgr.properties
      - $PWD/common/labcas-backend-common-0.7.jar:/usr/local/oodt/cas-filemgr/lib/labcas-backend-common-0.7.jar
    volumes_from:
      - labcas_rnaseq_app
    networks:
      default:
        aliases:
          - oodt.filemgr.host

  # OODT Workflow Manager + LabCAS configuration
  oodt_wmgr_app:
    env_file: labcas.env
    environment:
      - RNASEQ_DATA_DIR=/data/EDRN
    image: oodthub/oodt-wmgr
    container_name: oodt_wmgr
    expose:
      - "9001"
    ports:
      - "9001:9001"
    volumes:
      - $PWD/wmgr/etc/workflow.properties:/usr/local/oodt/cas-workflow/etc/workflow.properties
      - $PWD/common/labcas-backend-common-0.7.jar:/usr/local/oodt/cas-workflow/lib/labcas-backend-common-0.7.jar
      - $PWD/data/EDRN:/data/EDRN
    volumes_from:
      - labcas_rnaseq_app
    networks:
      default:
        aliases:
          - oodt.wmgr.host

  # OODT Product Server
  oodt_fmprod_app:
    env_file: labcas.env
    image: oodthub/oodt-fmprod
    container_name: oodt_fmprod
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes_from:
      - labcas_rnaseq_app
    networks:
      default:
        aliases:
          - oodt.fmprod.host

  # LabCAS rnaseq workflow
  # provides workflow+product configuration to the FM, WM services
  labcas_rnaseq_app:
    image: oodthub/labcas-rnaseq-test
    container_name: labcas_rnaseq
