# OODT-in-the-cloud system

version: '2'

services:

  oodt_filemgr_app:
    image: oodthub/oodt-filemgr
    container_name: oodt.filemgr.host
    #container_name: oodt_filemgr
    expose:
      - "9000"
      - "8983"
  #  ports:
  #    - "8983:8983"
  #    - "9000:9000"

  oodt_wmgr_app:
    image: oodthub/oodt-wmgr
    #container_name: oodt_wmgr
    expose:
      - "9001"
    #ports:
    #  - "9001:9001"
    #links:
    #  - oodt_filemgr_app:oodt.filemgr.host

networks:
  default:
    external:
      name: swarm-network
