#!sh
mkdir -p /usr/local/labcas_staging/ERR164552
cp *.sra /usr/local/labcas_staging/ERR164552
cp *.fastq /usr/local/labcas_staging/ERR164552
cp *.bt2 /usr/local/labcas_staging/ERR164552
cp *.gtf /usr/local/labcas_staging/ERR164552
cp *.fa /usr/local/labcas_staging/ERR164552
cp thout/*.counts /usr/local/labcas_staging/ERR164552
cp thout/*.bam /usr/local/labcas_staging/ERR164552
cp thout/*.sam /usr/local/labcas_staging/ERR164552
ls -l /usr/local/labcas_staging/ERR164552

