# Docker image containing basic LabCAS environment.
# The LabCAS environment is superimposed onto the OODT environment

FROM oodthub/oodt-node

MAINTAINER Luca Cinquini <luca.cinquini@jpl.nasa.gov>

ENV LABCAS_HOME $OODT_HOME
ENV LABCAS_ARCHIVE $OODT_ARCHIVE
ENV LABCAS_STAGING $OODT_STAGING
ENV LABCAS_CONFIG $OODT_CONFIG
