# Docker image that contains the OODT Workflow Manager configured to run the test-workflow,
# including the required PGEs
# For now, this image extends oodthub.oodt-wmgr so it can be deployed standalone on different hosts

FROM oodthub/oodt-wmgr

MAINTAINER Luca Cinquini <luca.cinquini@jpl.nasa.gov>

# add wmgr client script to run N workflows
COPY wmgr_config/scripts/run_workflows.sh $OODT_HOME/cas-workflow/bin/run_workflows.sh

# override entrypoint to avoid starting the Workflow manager, but keep the container running
ENTRYPOINT ["tail", "-f", "/dev/null"]
