# Docker image for SMAP SPDM installation. Includes:

FROM oodthub/spdm-services:0.3

MAINTAINER Cynthia L. Wong <cynthia.l.wong@jpl.nasa.gov>

#
# start stubs automatically
#
COPY scripts/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
CMD ["/usr/local/bin/docker-entrypoint.sh"]
