# Docker image that contains an OODT File Manager configured with the TestFile product type.

FROM oodthub/oodt-filemgr

MAINTAINER Luca Cinquini <luca.cinquini@jpl.nasa.gov>

# install custom OODT File Manager configuration
RUN mkdir -p $OODT_CONFIG/test-workflow
COPY filemgr_config/test-workflow/policy/ $OODT_CONFIG/test-workflow/policy/

# create final OODT archive directory
RUN mkdir -p  $OODT_ARCHIVE/test-workflow
