# docker-compose file for executing an OODT test workflow
# NOTE: this file assumes the pre-existence of an external network called 'mynetwork' (on a single host):
# docker network create mynetwork

version: '2'

networks:
  mynet:
    external:
      name: mynetwork

services:

  oodt_filemgr_app:
    image: oodthub/oodt-filemgr
    container_name: oodt_filemgr
    expose:
      - "9000"
      - "8983"
    ports:
      - "8983:8983"
      - "9000:9000"
    volumes_from:
      - oodt_test_workflow_app

  oodt_wmgr_app:
    image: oodthub/oodt-wmgr
    #container_name: oodt_wmgr
    expose:
      - "9001"
    ports:
      - "9001"
    links:
      - oodt_filemgr_app:oodt.filemgr.host
    volumes_from:
      - oodt_test_workflow_app
    environment:
      - "FILEMGR_URL=http://oodt.filemgr.host:9000"
    networks:
      default: {}
      mynet:
        aliases:
          - oodt.wmgr.host

  oodt_fmprod_app:
    image: oodthub/oodt-fmprod
    container_name: oodt_fmprod
    expose:
      - "8080"
    ports:
      - "8080:8080"
    links:
      - oodt_filemgr_app:oodt.filemgr.host
    volumes_from:
      - oodt_test_workflow_app
    environment:
      - "FILEMGR_URL=http://oodt.filemgr.host:9000"

  oodt_test_workflow_app:
    image: oodthub/oodt-example-compose
    container_name: oodt_example_compose
