# docker-compose file for executing an OODT test workflow

version: '2'

networks:
  mynetwork:
    driver: bridge

services:

  # OODT file manager
  oodt_filemgr_app:
    image: oodthub/oodt-filemgr
    container_name: myfilemgr
    expose:
      - "9000"
      - "8983"
    ports:
      - "8983:8983"
      - "9000:9000"
    volumes_from:
      - oodt_test_workflow_app
    networks:
      default: {}
      mynetwork:
        aliases:
          - oodt.filemgr.host

  # OODT workflow manager
  oodt_wmgr_app:
    image: oodthub/oodt-wmgr
    #container_name: mywmgr
    expose:
      - "9001"
    ports:
      - "9001"
    volumes_from:
      - oodt_test_workflow_app
    environment:
      - "FILEMGR_URL=http://oodt.filemgr.host:9000"
    networks:
      default: {}
      mynetwork:
        aliases:
          - oodt.wmgr.host

  # workflow manager container used as client to workflow manager server instances
  oodt_wmgr_client_app:
    image: oodthub/oodt-wmgr
    container_name: mywmgr_client
    environment:
      - "WORKFLOW_URL=http://oodt.wmgr.host:9001"
    # keep container running
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      default: {}
      mynetwork: {}

  # OODT product server
  oodt_fmprod_app:
    image: oodthub/oodt-fmprod
    container_name: myfmprod
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes_from:
      - oodt_test_workflow_app
    environment:
      - "FILEMGR_URL=http://oodt.filemgr.host:9000"
    networks:
      default: {}
      mynetwork:
        aliases:
          - oodt.fmprod.host

  oodt_test_workflow_app:
    image: oodthub/oodt-example-compose
    container_name: myapp
