# Docker image for running the ECOSTRESS workflows.
#
# This image extends oodthub/oodt-wmgr 
# by adding the ECOSTRESS specific configuration for the Workflow Manager

FROM oodthub/oodt-wmgr

MAINTAINER Luca Cinquini <luca.cinquini@jpl.nasa.gov>

# create final OODT archive directory
RUN mkdir -p  $OODT_ARCHIVE/ecostress

# install custom OODT Workflow Manager configuration
COPY wmgr_config/policy/ $OODT_CONFIG/ecostress/policy/
COPY wmgr_config/pge-configs/ $OODT_CONFIG/ecostress/pge-configs/

# install custom PGEs
RUN mkdir -p $PGE_ROOT/ecostress/
COPY wmgr_config/pges/ $PGE_ROOT/ecostress/

# install rabbitmq clients
COPY rabbitmq_clients/ $OODT_HOME/rabbitmq/

# FIXME: install custom scripts to start/stop workflow manager and rabbitmq clients
COPY scripts/ /usr/local/bin/

VOLUME $OODT_CONFIG
VOLUME $PGE_ROOT
VOLUME $OODT_ARCHIVE
VOLUME /usr/local/bin

# start the workflow manager (but no rabbitmq consumers)
ENTRYPOINT ["/usr/local/bin/start.sh"]
