# docker-compose file for executing the ECOSTRESS mock workflows

version: '2'

services:

  # OODT file manager
  filemgr:
    image: oodthub/oodt-filemgr
    container_name: filemgr
    expose:
      - "9000"
      - "8983"
    ports:
      - "8983:8983"
      - "9000:9000"
    volumes:
     - oodt_archive:/usr/local/oodt/archive
     - oodt_config:/usr/local/oodt/workflows
    networks:
      default:
        aliases:
          - oodt.filemgr.host

  # OODT workflow managers: one for L3a and one for L3b processing
  head_node:
    image: oodthub/ecostress-node
    expose:
      - "9001"
    ports:
      - "9001"
    volumes:
     - oodt_archive:/usr/local/oodt/archive
     - oodt_config:/usr/local/oodt/workflows
    depends_on:
      - rabbitmq
    environment:
      - "FILEMGR_URL=http://oodt.filemgr.host:9000"
      - "RABBITMQ_USER_URL=amqp://oodt-user:changeit@oodt.rabbitmq.host/%2f"
      - "RABBITMQ_ADMIN_URL=http://oodt-admin:changeit@localhost:15672"
    networks:
      default:
    entrypoint: ["/usr/local/bin/start.sh", "ecostress-L3a-workflow"]

  compute_node:
    image: oodthub/ecostress-node
    expose:
      - "9001"
    ports:
      - "9001"
    volumes:
     - oodt_archive:/usr/local/oodt/archive
     - oodt_config:/usr/local/oodt/workflows
    depends_on:
      - rabbitmq
    environment:
      - "FILEMGR_URL=http://oodt.filemgr.host:9000"
      - "RABBITMQ_USER_URL=amqp://oodt-user:changeit@oodt.rabbitmq.host/%2f"
      - "RABBITMQ_ADMIN_URL=http://oodt-admin:changeit@localhost:15672"
    networks:
      default:
    entrypoint: ["/usr/local/bin/start.sh", "ecostress-L3b-workflow", "ecostress-L4-workflow"]

  # OODT product server
  fmprod:
    image: oodthub/oodt-fmprod
    container_name: fmprod
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
     - oodt_archive:/usr/local/oodt/archive
    environment:
      - "FILEMGR_URL=http://oodt.filemgr.host:9000"
    networks:
      default:
        aliases:
          - oodt.fmprod.host

  # RabbitMQ server
  rabbitmq:
    image: oodthub/oodt-rabbitmq
    container_name: rabbitmq
    expose:
      - "5672"
      - "15672"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      default:
        aliases:
          - oodt.rabbitmq.host

# persistent data volumes
volumes:
  # permanent data storage
  oodt_archive:
  # FM and WM configuration, part of oodthub/ecostress-node
  oodt_config:
